language: node_js

install:
  - npm ci
  - npm i -g codecov

script:
  - npm -v
  - node -v
  - npm run-script build
  - npm run-script test:cover
  - codecov

notifications:
  email:
    on_success: never
